=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-01-05
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module PersonaAPIClient
  class InquiryAttributes
    # Birthdate, must be in the format \"YYYY-MM-DD\".
    attr_accessor :birthdate

    # Given or first name.
    attr_accessor :name_first

    # Middle name.
    attr_accessor :name_middle

    # Family or last name.
    attr_accessor :name_last

    # Phone number.
    attr_accessor :phone_number

    # Email address.
    attr_accessor :email_address

    # Street name of residence address.
    attr_accessor :address_street_1

    # Extension of residence address, usually apartment or suite number.
    attr_accessor :address_street_2

    # City of residence address. Not all international addresses use this attribute.
    attr_accessor :address_city

    # State or subdivision of residence address. In the US, this should be the unabbreviated name. Not all international addresses use this attribute.
    attr_accessor :address_subdivision

    # ZIP or postal code of residence address. Not all international addresses use this attribute.
    attr_accessor :address_postal_code

    # The status of the Inquiry  Possible values: - created - pending - completed - expired - failed - needs_review - approved - declined  Do not assume this is a static enumeration; Persona may add new values in the future without a versioned update.
    attr_accessor :status

    attr_accessor :reference_id

    attr_accessor :note

    attr_accessor :behaviors

    attr_accessor :tags

    attr_accessor :creator

    attr_accessor :reviewer_comment

    attr_accessor :created_at

    attr_accessor :updated_at

    attr_accessor :started_at

    attr_accessor :completed_at

    attr_accessor :failed_at

    attr_accessor :marked_for_review_at

    attr_accessor :decisioned_at

    attr_accessor :expired_at

    attr_accessor :redacted_at

    attr_accessor :previous_step_name

    attr_accessor :next_step_name

    # Social security number.
    attr_accessor :social_security_number

    attr_accessor :address_subdivision_abbr

    attr_accessor :address_postal_code_abbr

    attr_accessor :identification_number

    attr_accessor :fields

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'birthdate' => :'birthdate',
        :'name_first' => :'name-first',
        :'name_middle' => :'name-middle',
        :'name_last' => :'name-last',
        :'phone_number' => :'phone-number',
        :'email_address' => :'email-address',
        :'address_street_1' => :'address-street-1',
        :'address_street_2' => :'address-street-2',
        :'address_city' => :'address-city',
        :'address_subdivision' => :'address-subdivision',
        :'address_postal_code' => :'address-postal-code',
        :'status' => :'status',
        :'reference_id' => :'reference-id',
        :'note' => :'note',
        :'behaviors' => :'behaviors',
        :'tags' => :'tags',
        :'creator' => :'creator',
        :'reviewer_comment' => :'reviewer-comment',
        :'created_at' => :'created-at',
        :'updated_at' => :'updated-at',
        :'started_at' => :'started-at',
        :'completed_at' => :'completed-at',
        :'failed_at' => :'failed-at',
        :'marked_for_review_at' => :'marked-for-review-at',
        :'decisioned_at' => :'decisioned-at',
        :'expired_at' => :'expired-at',
        :'redacted_at' => :'redacted-at',
        :'previous_step_name' => :'previous-step-name',
        :'next_step_name' => :'next-step-name',
        :'social_security_number' => :'social-security-number',
        :'address_subdivision_abbr' => :'address-subdivision-abbr',
        :'address_postal_code_abbr' => :'address-postal-code-abbr',
        :'identification_number' => :'identification-number',
        :'fields' => :'fields'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'birthdate' => :'Date',
        :'name_first' => :'String',
        :'name_middle' => :'String',
        :'name_last' => :'String',
        :'phone_number' => :'String',
        :'email_address' => :'String',
        :'address_street_1' => :'String',
        :'address_street_2' => :'String',
        :'address_city' => :'String',
        :'address_subdivision' => :'String',
        :'address_postal_code' => :'String',
        :'status' => :'String',
        :'reference_id' => :'String',
        :'note' => :'String',
        :'behaviors' => :'InquiryAttributesAllOfBehaviors',
        :'tags' => :'Array<String>',
        :'creator' => :'String',
        :'reviewer_comment' => :'String',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'started_at' => :'Time',
        :'completed_at' => :'Time',
        :'failed_at' => :'Time',
        :'marked_for_review_at' => :'Time',
        :'decisioned_at' => :'Time',
        :'expired_at' => :'Time',
        :'redacted_at' => :'Time',
        :'previous_step_name' => :'String',
        :'next_step_name' => :'String',
        :'social_security_number' => :'String',
        :'address_subdivision_abbr' => :'String',
        :'address_postal_code_abbr' => :'String',
        :'identification_number' => :'String',
        :'fields' => :'InquiryAttributesAllOfFields'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'DefaultFields'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PersonaAPIClient::InquiryAttributes` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PersonaAPIClient::InquiryAttributes`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'birthdate')
        self.birthdate = attributes[:'birthdate']
      end

      if attributes.key?(:'name_first')
        self.name_first = attributes[:'name_first']
      end

      if attributes.key?(:'name_middle')
        self.name_middle = attributes[:'name_middle']
      end

      if attributes.key?(:'name_last')
        self.name_last = attributes[:'name_last']
      end

      if attributes.key?(:'phone_number')
        self.phone_number = attributes[:'phone_number']
      end

      if attributes.key?(:'email_address')
        self.email_address = attributes[:'email_address']
      end

      if attributes.key?(:'address_street_1')
        self.address_street_1 = attributes[:'address_street_1']
      end

      if attributes.key?(:'address_street_2')
        self.address_street_2 = attributes[:'address_street_2']
      end

      if attributes.key?(:'address_city')
        self.address_city = attributes[:'address_city']
      end

      if attributes.key?(:'address_subdivision')
        self.address_subdivision = attributes[:'address_subdivision']
      end

      if attributes.key?(:'address_postal_code')
        self.address_postal_code = attributes[:'address_postal_code']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'reference_id')
        self.reference_id = attributes[:'reference_id']
      end

      if attributes.key?(:'note')
        self.note = attributes[:'note']
      end

      if attributes.key?(:'behaviors')
        self.behaviors = attributes[:'behaviors']
      end

      if attributes.key?(:'tags')
        if (value = attributes[:'tags']).is_a?(Array)
          self.tags = value
        end
      end

      if attributes.key?(:'creator')
        self.creator = attributes[:'creator']
      end

      if attributes.key?(:'reviewer_comment')
        self.reviewer_comment = attributes[:'reviewer_comment']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'started_at')
        self.started_at = attributes[:'started_at']
      end

      if attributes.key?(:'completed_at')
        self.completed_at = attributes[:'completed_at']
      end

      if attributes.key?(:'failed_at')
        self.failed_at = attributes[:'failed_at']
      end

      if attributes.key?(:'marked_for_review_at')
        self.marked_for_review_at = attributes[:'marked_for_review_at']
      end

      if attributes.key?(:'decisioned_at')
        self.decisioned_at = attributes[:'decisioned_at']
      end

      if attributes.key?(:'expired_at')
        self.expired_at = attributes[:'expired_at']
      end

      if attributes.key?(:'redacted_at')
        self.redacted_at = attributes[:'redacted_at']
      end

      if attributes.key?(:'previous_step_name')
        self.previous_step_name = attributes[:'previous_step_name']
      end

      if attributes.key?(:'next_step_name')
        self.next_step_name = attributes[:'next_step_name']
      end

      if attributes.key?(:'social_security_number')
        self.social_security_number = attributes[:'social_security_number']
      end

      if attributes.key?(:'address_subdivision_abbr')
        self.address_subdivision_abbr = attributes[:'address_subdivision_abbr']
      end

      if attributes.key?(:'address_postal_code_abbr')
        self.address_postal_code_abbr = attributes[:'address_postal_code_abbr']
      end

      if attributes.key?(:'identification_number')
        self.identification_number = attributes[:'identification_number']
      end

      if attributes.key?(:'fields')
        self.fields = attributes[:'fields']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          birthdate == o.birthdate &&
          name_first == o.name_first &&
          name_middle == o.name_middle &&
          name_last == o.name_last &&
          phone_number == o.phone_number &&
          email_address == o.email_address &&
          address_street_1 == o.address_street_1 &&
          address_street_2 == o.address_street_2 &&
          address_city == o.address_city &&
          address_subdivision == o.address_subdivision &&
          address_postal_code == o.address_postal_code &&
          status == o.status &&
          reference_id == o.reference_id &&
          note == o.note &&
          behaviors == o.behaviors &&
          tags == o.tags &&
          creator == o.creator &&
          reviewer_comment == o.reviewer_comment &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          started_at == o.started_at &&
          completed_at == o.completed_at &&
          failed_at == o.failed_at &&
          marked_for_review_at == o.marked_for_review_at &&
          decisioned_at == o.decisioned_at &&
          expired_at == o.expired_at &&
          redacted_at == o.redacted_at &&
          previous_step_name == o.previous_step_name &&
          next_step_name == o.next_step_name &&
          social_security_number == o.social_security_number &&
          address_subdivision_abbr == o.address_subdivision_abbr &&
          address_postal_code_abbr == o.address_postal_code_abbr &&
          identification_number == o.identification_number &&
          fields == o.fields
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [birthdate, name_first, name_middle, name_last, phone_number, email_address, address_street_1, address_street_2, address_city, address_subdivision, address_postal_code, status, reference_id, note, behaviors, tags, creator, reviewer_comment, created_at, updated_at, started_at, completed_at, failed_at, marked_for_review_at, decisioned_at, expired_at, redacted_at, previous_step_name, next_step_name, social_security_number, address_subdivision_abbr, address_postal_code_abbr, identification_number, fields].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = PersonaAPIClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
