=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-01-05
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module PersonaAPIClient
  class VerificationSelfieAttributesAllOfCenterPhotoFaceCoordinates
    attr_accessor :top_left

    attr_accessor :top_right

    attr_accessor :bottom_left

    attr_accessor :bottom_right

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'top_left' => :'top-left',
        :'top_right' => :'top-right',
        :'bottom_left' => :'bottom-left',
        :'bottom_right' => :'bottom-right'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'top_left' => :'Array<Float>',
        :'top_right' => :'Array<Float>',
        :'bottom_left' => :'Array<Float>',
        :'bottom_right' => :'Array<Float>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PersonaAPIClient::VerificationSelfieAttributesAllOfCenterPhotoFaceCoordinates` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PersonaAPIClient::VerificationSelfieAttributesAllOfCenterPhotoFaceCoordinates`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'top_left')
        if (value = attributes[:'top_left']).is_a?(Array)
          self.top_left = value
        end
      end

      if attributes.key?(:'top_right')
        if (value = attributes[:'top_right']).is_a?(Array)
          self.top_right = value
        end
      end

      if attributes.key?(:'bottom_left')
        if (value = attributes[:'bottom_left']).is_a?(Array)
          self.bottom_left = value
        end
      end

      if attributes.key?(:'bottom_right')
        if (value = attributes[:'bottom_right']).is_a?(Array)
          self.bottom_right = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@top_left.nil? && @top_left.length > 2
        invalid_properties.push('invalid value for "top_left", number of items must be less than or equal to 2.')
      end

      if !@top_left.nil? && @top_left.length < 2
        invalid_properties.push('invalid value for "top_left", number of items must be greater than or equal to 2.')
      end

      if !@top_right.nil? && @top_right.length > 2
        invalid_properties.push('invalid value for "top_right", number of items must be less than or equal to 2.')
      end

      if !@top_right.nil? && @top_right.length < 2
        invalid_properties.push('invalid value for "top_right", number of items must be greater than or equal to 2.')
      end

      if !@bottom_left.nil? && @bottom_left.length > 2
        invalid_properties.push('invalid value for "bottom_left", number of items must be less than or equal to 2.')
      end

      if !@bottom_left.nil? && @bottom_left.length < 2
        invalid_properties.push('invalid value for "bottom_left", number of items must be greater than or equal to 2.')
      end

      if !@bottom_right.nil? && @bottom_right.length > 2
        invalid_properties.push('invalid value for "bottom_right", number of items must be less than or equal to 2.')
      end

      if !@bottom_right.nil? && @bottom_right.length < 2
        invalid_properties.push('invalid value for "bottom_right", number of items must be greater than or equal to 2.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@top_left.nil? && @top_left.length > 2
      return false if !@top_left.nil? && @top_left.length < 2
      return false if !@top_right.nil? && @top_right.length > 2
      return false if !@top_right.nil? && @top_right.length < 2
      return false if !@bottom_left.nil? && @bottom_left.length > 2
      return false if !@bottom_left.nil? && @bottom_left.length < 2
      return false if !@bottom_right.nil? && @bottom_right.length > 2
      return false if !@bottom_right.nil? && @bottom_right.length < 2
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] top_left Value to be assigned
    def top_left=(top_left)
      if top_left.nil?
        fail ArgumentError, 'top_left cannot be nil'
      end

      if top_left.length > 2
        fail ArgumentError, 'invalid value for "top_left", number of items must be less than or equal to 2.'
      end

      if top_left.length < 2
        fail ArgumentError, 'invalid value for "top_left", number of items must be greater than or equal to 2.'
      end

      @top_left = top_left
    end

    # Custom attribute writer method with validation
    # @param [Object] top_right Value to be assigned
    def top_right=(top_right)
      if top_right.nil?
        fail ArgumentError, 'top_right cannot be nil'
      end

      if top_right.length > 2
        fail ArgumentError, 'invalid value for "top_right", number of items must be less than or equal to 2.'
      end

      if top_right.length < 2
        fail ArgumentError, 'invalid value for "top_right", number of items must be greater than or equal to 2.'
      end

      @top_right = top_right
    end

    # Custom attribute writer method with validation
    # @param [Object] bottom_left Value to be assigned
    def bottom_left=(bottom_left)
      if bottom_left.nil?
        fail ArgumentError, 'bottom_left cannot be nil'
      end

      if bottom_left.length > 2
        fail ArgumentError, 'invalid value for "bottom_left", number of items must be less than or equal to 2.'
      end

      if bottom_left.length < 2
        fail ArgumentError, 'invalid value for "bottom_left", number of items must be greater than or equal to 2.'
      end

      @bottom_left = bottom_left
    end

    # Custom attribute writer method with validation
    # @param [Object] bottom_right Value to be assigned
    def bottom_right=(bottom_right)
      if bottom_right.nil?
        fail ArgumentError, 'bottom_right cannot be nil'
      end

      if bottom_right.length > 2
        fail ArgumentError, 'invalid value for "bottom_right", number of items must be less than or equal to 2.'
      end

      if bottom_right.length < 2
        fail ArgumentError, 'invalid value for "bottom_right", number of items must be greater than or equal to 2.'
      end

      @bottom_right = bottom_right
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          top_left == o.top_left &&
          top_right == o.top_right &&
          bottom_left == o.bottom_left &&
          bottom_right == o.bottom_right
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [top_left, top_right, bottom_left, bottom_right].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = PersonaAPIClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
