# To update:

# rm -rf *.gem docs lib spec
# curl https://raw.githubusercontent.com/persona-id/persona-openapi/refs/heads/main/openapi-bundled.yaml -O
# openapi-generator generate --config openapi_generator_config.yml

inputSpec: openapi-bundled.yaml
generatorName: ruby
output: .
additionalProperties:
  gemName: "persona_api_client"
  gemAuthor: "Hey Jane"
  gemAuthorEmail: "eng_product@heyjane.co"
  gemLicense: "MIT"
  gemRequiredRubyVersion: "~> 3.0"
  gemVersion: "1.1.0"
  library: "faraday"
  moduleName: "PersonaAPIClient"
  useAutoload: true
