=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-01-05
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::InquirySessionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InquirySessionsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::InquirySessionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InquirySessionsApi' do
    it 'should create an instance of InquirySessionsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::InquirySessionsApi)
    end
  end

  # unit tests for create_an_inquiry_session
  # Create an Inquiry Session
  # Creates a new Inquiry Session. By default, we only allow up to 25 sessions per Inquiry.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/reference/serialization#inclusion-of-related-resources) for more details.
  # @option opts [CreateAnInquirySessionRequest] :create_an_inquiry_session_request 
  # @return [CreateAnInquirySession201Response]
  describe 'create_an_inquiry_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for expire_an_inquiry_session
  # Expire an Inquiry Session
  # Expires a specific Inquiry Session.
  # @param inquiry_session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/reference/serialization#inclusion-of-related-resources) for more details.
  # @return [CreateAnInquirySession201Response]
  describe 'expire_an_inquiry_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for expire_inquiry_sessions
  # Expire Inquiry Sessions
  # Expires all active Inquiry Sessions for a given set of Inquiries.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/reference/serialization#inclusion-of-related-resources) for more details.
  # @option opts [ExpireInquirySessionsRequest] :expire_inquiry_sessions_request 
  # @return [ExpireInquirySessions200Response]
  describe 'expire_inquiry_sessions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for generate_a_one_time_link_for_an_inquiry_session
  # Generate a one-time link for Inquiry Session
  # Generates a one-time link for a specific Inquiry Session.
  # @param inquiry_session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/reference/serialization#inclusion-of-related-resources) for more details.
  # @return [GenerateAOneTimeLinkForAnInquirySession200Response]
  describe 'generate_a_one_time_link_for_an_inquiry_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_all_inquiry_sessions
  # List all Inquiry Sessions
  # Retrieves a list of Inquiry Sessions.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [ListAllInquirySessionsFilterParameter] :filter 
  # @return [ListAllInquirySessions200Response]
  describe 'list_all_inquiry_sessions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_an_inquiry_session
  # Retrieve an Inquiry Session
  # Retrieves details of a specific Inquiry Session.
  # @param inquiry_session_id Inquiry session ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/reference/serialization#inclusion-of-related-resources) for more details.
  # @return [CreateAnInquirySession201Response]
  describe 'retrieve_an_inquiry_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
