=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-01-05
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::TransactionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TransactionsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::TransactionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransactionsApi' do
    it 'should create an instance of TransactionsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::TransactionsApi)
    end
  end

  # unit tests for create_a_transaction
  # Create a Transaction
  # Creates a new &lt;&lt;glossary:Transaction&gt;&gt; for a specific &lt;&lt;glossary:transaction type&gt;&gt; in your organization.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/reference/serialization#inclusion-of-related-resources) for more details.
  # @option opts [CreateATransactionRequest] :create_a_transaction_request 
  # @return [CreateATransaction200Response]
  describe 'create_a_transaction test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_a_transaction_label
  # Create a Transaction label
  # Create a new label for an existing &lt;&lt;glossary:Transaction&gt;&gt;.
  # @param transaction_id ID of the transaction to create a label for.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/reference/serialization#inclusion-of-related-resources) for more details.
  # @option opts [CreateATransactionLabelRequest] :create_a_transaction_label_request 
  # @return [UpdateATransaction200Response]
  describe 'create_a_transaction_label test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_all_transactions
  # List all Transactions
  # Returns a list of your organization&#39;s transactions. Note that this endpoint aggregates transactions across all &lt;&lt;glossary:transaction type&gt;&gt;(s). See [Pagination](https://docs.withpersona.com/reference/pagination) for more details about handling the response.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [ListAllAccountsPageParameter] :page 
  # @option opts [ListAllTransactionsFilterParameter] :filter 
  # @return [ListAllTransactions200Response]
  describe 'list_all_transactions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for redact_a_transaction
  # Redact a Transaction
  # Permanently deletes personally identifiable information (PII) for a &lt;&lt;glossary:Transaction&gt;&gt;. The response indicates a successful redaction of the Transaction. Redaction of the Transaction&#39;s associated child objects are done asynchronously and may take some time before all associated child objects are fully redacted. **This action cannot be undone**.
  # @param transaction_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/reference/serialization#inclusion-of-related-resources) for more details.
  # @return [CreateATransaction200Response]
  describe 'redact_a_transaction test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for redact_transaction_biometrics
  # Redact Transaction biometrics
  # Permanently deletes biometric data for a &lt;&lt;glossary:Transaction&gt;&gt; AND all its associated objects. **This action cannot be undone**.
  # @param transaction_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/reference/serialization#inclusion-of-related-resources) for more details.
  # @return [CreateATransaction200Response]
  describe 'redact_transaction_biometrics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_a_transaction
  # Retrieve a Transaction
  # Retrieves the details of an existing &lt;&lt;glossary:Transaction&gt;&gt;.
  # @param transaction_id ID of the transaction to retrieve.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/reference/serialization#inclusion-of-related-resources) for more details.
  # @return [RetrieveATransaction200Response]
  describe 'retrieve_a_transaction test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for transactions_add_tag
  # Add tag to Transaction
  # Adds a tag to a Transaction. Create a new tag if the tag does not already exist. No effect if the transaction already has the tag.
  # @param transaction_id ID of the transaction to add tag on.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/reference/serialization#inclusion-of-related-resources) for more details.
  # @option opts [TransactionsAddTagRequest] :transactions_add_tag_request 
  # @return [CreateATransaction200Response]
  describe 'transactions_add_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for transactions_remove_tag
  # Remove tag from a Transaction
  # Remove a tag from a transaction. No effect if the transaction does not have the tag.
  # @param transaction_id ID of the transaction to remove tag from.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/reference/serialization#inclusion-of-related-resources) for more details.
  # @option opts [TransactionsAddTagRequest] :transactions_add_tag_request 
  # @return [CreateATransaction200Response]
  describe 'transactions_remove_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for transactions_set_tags
  # Sets tags on a Transaction
  # Set the list of tags on a transaction. Remove all tags on the transaction that don&#39;t appear on the list. Add all tags on the transaction from the list.
  # @param transaction_id ID of the transaction to set tags on.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/reference/serialization#inclusion-of-related-resources) for more details.
  # @option opts [TransactionsSetTagsRequest] :transactions_set_tags_request 
  # @return [CreateATransaction200Response]
  describe 'transactions_set_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_a_transaction
  # Update a Transaction
  # Updates a &lt;&lt;glossary:Transaction&gt;&gt; that has been previously created.
  # @param transaction_id ID of the transaction to update.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_inflection Determines casing for the API response
  # @option opts [String] :idempotency_key Ensures the request is idempotent
  # @option opts [String] :persona_version 
  # @option opts [String] :include A comma-separated list of relationship paths. This can be used to customize which related resources will be fully serialized in the &#x60;included&#x60; key in the response. See [Serialization](https://docs.withpersona.com/reference/serialization#inclusion-of-related-resources) for more details.
  # @option opts [UpdateATransactionRequest] :update_a_transaction_request 
  # @return [UpdateATransaction200Response]
  describe 'update_a_transaction test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
