=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-01-05
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::AccountAttributesAllOfIdentificationNumbersValue
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::AccountAttributesAllOfIdentificationNumbersValue do
  let(:instance) { OpenapiClient::AccountAttributesAllOfIdentificationNumbersValue.new }

  describe 'test an instance of AccountAttributesAllOfIdentificationNumbersValue' do
    it 'should create an instance of AccountAttributesAllOfIdentificationNumbersValue' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::AccountAttributesAllOfIdentificationNumbersValue)
    end
  end

end
