=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-01-05
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PersonaAPIClient::InlineObject5ErrorsInnerSource
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PersonaAPIClient::InlineObject5ErrorsInnerSource do
  let(:instance) { PersonaAPIClient::InlineObject5ErrorsInnerSource.new }

  describe 'test an instance of InlineObject5ErrorsInnerSource' do
    it 'should create an instance of InlineObject5ErrorsInnerSource' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PersonaAPIClient::InlineObject5ErrorsInnerSource)
    end
  end

  describe 'test attribute "pointer"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
