=begin
#Persona API Reference

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2023-01-05
Contact: support@withpersona.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::RedactAnAccount409ResponseOneOfErrorsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::RedactAnAccount409ResponseOneOfErrorsInner do
  let(:instance) { OpenapiClient::RedactAnAccount409ResponseOneOfErrorsInner.new }

  describe 'test an instance of RedactAnAccount409ResponseOneOfErrorsInner' do
    it 'should create an instance of RedactAnAccount409ResponseOneOfErrorsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::RedactAnAccount409ResponseOneOfErrorsInner)
    end
  end

  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "details"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
